export const CHANGE_CRACKER_COMPOSITION = "CHANGE_CRACKER_COMPOSITION";
export const ADD_CRACKER_TO_BASKET = "ADD_CRACKER_TO_BASKET";
export const DELETE_CRACKER_FROM_BASKET = "DELETE_CRACKER_FROM_BASKET";
export const CHANGE_PACK = "CHANGE_PACK";
export const SHOW_SHOPPING_CART = "SHOW_SHOPPING_CART";
export const SET_IS_MOBILE_VERSION = "SET_IS_MOBILE_VERSION";
export const SET_ADAPTIVE_FOOTER_BACGROUND = "SET_ADAPTIVE_FOOTER_BACGROUND";
export const SET_IS_ACTIVE_MENU = "SET_IS_ACTIVE_MENU";
